# 应用名称
name: spring-cloud-event-sourcing-example

# 镜像地址
Image_config: 10.0.160.9:5000/kbastani-config-service
Image_hystrix-dashboard: 10.0.160.9:5000/kbastani-hystrix-dashboard
Image_zipkin: 10.0.160.9:5000/zipkin:2
Image_mysql: 10.0.160.9:5000/mysql:5.7
Image_neo4j: 10.0.160.9:5000/neo4j:3.3
Image_mongo: 10.0.160.9:5000/mongo:3.3
Image_redis: 10.0.160.9:5000/redis:3.0
Image_user: 10.0.160.9:5000/kbastani-user-service
Image_discovery: 10.0.160.9:5000/kbastani-discovery-service
Image_edge: 10.0.160.9:5000/kbastani-edge-service
Image_account: 10.0.160.9:5000/kbastani-account-service
Image_inventory: 10.0.160.9:5000/kbastani-inventory-service
Image_order: 10.0.160.9:5000/kbastani-order-service
Image_catalog: 10.0.160.9:5000/kbastani-catalog-service
Image_shopping-cart: 10.0.160.9:5000/kbastani-shopping-cart-service
Image_online-store-web: 10.0.160.9:5000/kbastani-online-store-web

# 镜像下载策略：IfNotPresent（本地没有即下载）、Always（始终重新下载）
imagePullPolicy: IfNotPresent

# ALB 名称
ALB_NAME: nginx-10-0-160-9

# ALB IP 地址
ALB_IP: 10.0.160.9

# Config Server 使用的 Git 仓库地址
GIT_URL: https://github.com/jcloud6/spring-cloud-event-sourcing-config

# Config Server 使用的 Git 仓库账号
GIT_USER: alauda 

# Config Server 使用的 Git 仓库密码
GIT_PASS: alauda

# 应用加载的配置类型
SPRING_PROFILES_ACTIVE: docker
